[versions]
bline-lib = "v0.8.4"
caffeine = "3.2.4"
crunch = "2.0.3"
error-prone = "2.42.0"
error-prone-plugin = "5.1.0"
gradle-rio = "2026.2.1"
gversion = "1.10.3"
jspecify = "1.0.1"
junit = "6.1.0"
null-away = "0.13.4"
spotless = "8.5.1"

[plugins]
error-prone = { id = "net.ltgt.errorprone", version.ref = "error-prone-plugin" }
gradle-rio = { id = "edu.wpi.first.GradleRIO", version.ref = "gradle-rio" }
gversion = { id = "com.peterabeles.gversion", version.ref = "gversion" }
#noinspection UnusedVersionCatalogEntry
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }

[libraries]
bline-lib = { group = "com.github.edanliahovetsky", name = "BLine-Lib", version.ref = "bline-lib" }
caffeine = { group = "com.github.ben-manes.caffeine", name = "caffeine", version.ref = "caffeine" }
crunch = { group = "com.github.Redempt", name = "Crunch", version.ref = "crunch" }
error-prone-core = { group = "com.google.errorprone", name = "error_prone_core", version.ref = "error-prone" }
jspecify = { group = "org.jspecify", name = "jspecify", version.ref = "jspecify" }
junit-bom = { group = "org.junit", name = "junit-bom", version.ref = "junit" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher" }
#noinspection UnusedVersionCatalogEntry
null-away = { group = "com.uber.nullaway", name = "nullaway", version.ref = "null-away" }
